<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviour"
    nsURI="urn:behaviour/1.0" nsPrefix="behaviour">
  <eClassifiers xsi:type="ecore:EClass" name="Behaviour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//Block" containment="true" eOpposite="#//Block/parentBehaviour"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainActor" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//SystemActor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentBehaviour" lowerBound="1"
        eType="#//Behaviour" eOpposite="#//Behaviour/blocks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preState" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inMessage" lowerBound="1"
        eType="#//InMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//Activation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postState" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outMessages" upperBound="-1"
        eType="#//OutMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Return"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Return"/>
  </eClassifiers>
</ecore:EPackage>
