<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviour" nsURI="urn:behaviour/1.0" nsPrefix="behaviour">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="commonconcepts" value="CommonConcepts.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviourCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviour" upperBound="-1"
        eType="#//Behaviour" containment="true" eOpposite="#//Behaviour/collection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behaviour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" lowerBound="1"
        eType="#//BehaviourCollection" eOpposite="#//BehaviourCollection/behaviour"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainActor" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//SystemActor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
        eType="#//Block" containment="true" eOpposite="#//Block/parentBehaviour"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentBehaviour" lowerBound="1"
        eType="#//Behaviour" eOpposite="#//Behaviour/block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preState" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inMessage" lowerBound="1"
        eType="#//InMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activation" lowerBound="1"
        eType="#//Activation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postState" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outMessage" upperBound="-1"
        eType="#//OutMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Return" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" lowerBound="1"
        eType="ecore:EClass CommonConcepts.ecore#//Return" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
